### PR TITLE
adds dynamic open graph url, makes the twitter share a button with an ic...

### PR DESCRIPTION
**Pull request by alexkahn**
...on

### CODE REVIEW

**Comment by benwilhelm** [comment]
There's some inconsistent styling between the two buttons. Can we ditch the
padding/border/background for the wrapper around the twitter link?

[image: Inline image 1]

On Sun, Feb 1, 2015 at 11:38 AM, Alex Kahn <notifications@github.com> wrote:

> ...on
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/open-city/recycling/pull/112
> Commit Summary
>
>    - adds dynamic open graph url, makes the twitter share a button with
>    an icon
>
> File Changes
>
>    - *M* routes/index.js
>    <https://github.com/open-city/recycling/pull/112/files#diff-0> (12)
>    - *M* views/_header.ejs
>    <https://github.com/open-city/recycling/pull/112/files#diff-1> (2)
>    - *M* views/getinvolved.ejs
>    <https://github.com/open-city/recycling/pull/112/files#diff-2> (6)
>
> Patch Links:
>
>    - https://github.com/open-city/recycling/pull/112.patch
>    - https://github.com/open-city/recycling/pull/112.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/open-city/recycling/pull/112>.
>



-- 
Ben Wilhelm
ben@doublebeamdesign.com

**Comment by benwilhelm** [comment]
screen shot 2015-02-01 at 3 20 36 pm

**Comment by alexkahn** [comment]
@benwilhelm I've eliminated what looks like superfluous styling. I've never actually seen the widgets render - it just looked like a vanilla link on my end.

**Comment by alexkahn** [comment]
Just added a link to the github repo for the site per an issue someone filed.

**Pull request merged**
