### PR TITLE
delete

### PR DESCRIPTION
**Pull request by dsinns**

### CODE REVIEW

**Comment by luqmaan** [comment]
:fearful:

**Comment by matiaskitty** [comment]
Hi Austin people,

I see that you've made some pull requests for My Building Doesn't Recycle. That's very exciting. Let us  ( @benwilhelm, @alexkahn, and me ) know if you need any help or support. 

Best,
Claire

**Comment by luqmaan** [comment]
Thanks @matiaskitty. Do you guys run mongo, memcached and the actual app all on the same heroku instance?

**Comment by alexkahn** [comment]
Yes, everything is on one Heroku app.

**Comment by alexkahn** [comment]
It's all with add ons.

**Comment by luqmaan** [comment]
Cool, thanks for clarifying!

We spent a bunch of time trying to get it to run on Azure to no avail (since Code for America has that free Azure credit).

Yesterday we tried out Heroku, and things were very straightforward to setup (esp since you've already setup the environment variables :+1: ): http://mybuildingdoesntrecycle.herokuapp.com/

Digging deeper through the code, I think we'd like to simplify the app a little bit and get rid of the mongo/memcached dependency.

https://github.com/open-austin/recycling-bin

Do you have any feedback/suggestions?

I think the API really only needs only four endpoints (without the ward stuff):

https://github.com/open-austin/recycling-bin/issues/1

**Comment by alexkahn** [comment]
Well, you can use something like Redis to manage all of the data (depending on the amounts you collect) but I don't really see why you wouldn't want a database at all.

In all honesty, I'd like to totally redo many parts of the app - migrate over to Hapi.js for the server/api code, use something like React for the front-end, etc, etc..

Ideally, we could make this project a bit more general - that is, allow people to just change the templates and stylesheets with their own copy/branding to make it a simpler forking process (as I'm sure you're aware).

It would be really cool to work together on that stuff, let me know if we can move forward on that because I know that @matiaskitty is working on doing some data visualizations that I'm sure you'd also like for your endeavors.

**Comment by luqmaan** [comment]
Hmm, well if you were thinking about rewriting stuff, maybe we can work together on the fork/v2?

We haven't decided on a particular language for the backend of our fork, so I think we'd be hapi to use hapi.js.

I was also thinking of using React + react-leaflet for the frontend (we used them on https://github.com/open-austin/austingreenmap).

What sort of data visualizations were you thinking of doing?

Also, as far as the email/ward thing, I think that should live outside of the server and should be a cron job that can consumes the API. Austin doesn't have the idea of wards (we have districts, which seem much bigger), so we would need to change the way reporting works quite a bit.

If you are interested in working together on rewriting the app, do you want to take this convo to chat? http://slack.open-austin.org

**Pull request closed without merging**
