### PR TITLE
Captcha

### PR DESCRIPTION
**Pull request by alexkahn**
Adds a reCaptcha to the contact form so we can make sure that we don't accidently make appointments with robots.

### CODE REVIEW

**Comment by alexkahn** [comment]
Going to merge this because it was supposed to be simple fix for an issue.

**Comment by benwilhelm** [comment]
This is failing for me in localhost.  Do I need to add an API key as an environment variable or something?

    { success: false, 'error-codes': [ 'invalid-input-secret' ] }

**Comment by alexkahn** [comment]
Yes! Sorry about that.

**Comment by alexkahn** [comment]
@benwilhelm sent via gchat

**Pull request merged**
